config/routes.rb
Rails.application.routes.draw do
  get 'users/new'
  get 'users/create'
  get 'users/edit'
  get 'users/update'

  get 'errors/not_found'
  unauthenticated do
    root to: 'home#index_logged_out', as: :unauthenticated_root
  end


  authenticated :user do
    root to: 'game#index', as: :authenticated_root
  end

  # devise_for :users
  devise_for :users, :controllers => {:registrations => "registrations"}
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check
  get "squares/:id" => "squares#show"

  # Defines the root path route ("/")
  # root "posts#index"

  #Set the game page as the root route
  root 'game#index'
  get "game" => "game#index"

  post 'squares/:id/', to: 'squares#squares_words_logic', as: 'squares_words_logic'
  # post 'squares/:id/' => "squares#show"

 devise_scope :user do
    get 'sign_in', to: 'devise/sessions#new'
    get "sign_up" => "devise/registrations#new" 
    get '/users/sign_out' => 'devise/sessions#destroy'
  end

  # adds the route for the avatar page
  get "avatar"=> "users#get_avatars"
  post "avatar", to: "avatar#choose_avatar"
  post 'location' , to: 'game#location'
end

app/models/square.rb
class Square < ApplicationRecord
validates :lng, presence: true
  validates :lat, presence: true
  has_many :user_squares
  has_many :users, through: :user_squares

  # Example method
  def coordinates
    "Longitude: #{lng}, Latitude: #{lat}"
  end
end

app/controllers/squares_controller.rb
class SquaresController < ApplicationController
  before_action :authenticate_user! 
  include SquaresHelper

    def show
      @square = Square.find(params[:id])
      @user = current_user
      @user_square = UserSquare.find_or_initialize_by(user: @user, square: @square)
      bucket_name = 'ttsquaresdev'
      image_name = @user_square.image_path
      @s3_url = "https://#{bucket_name}.s3.amazonaws.com/#{image_name}"
      @display_words = get_display_words(@user_square.remaining_words , @square.words)
      @message = params[:message]
  end
    
  def squares_words_logic
    @square = Square.find(params[:id])
    user = current_user # this is the user that is logged in
    # add user id, square id, and remaining words to user_squares table
    @user_square = UserSquare.find_or_initialize_by(user: user, square: @square)
    remaining_words = get_remaining_words(@user_square.remaining_words)
    p @user_square
    # @user_square.remaining_words = remaining_words
    # @user_square.save

    # User guessed everything correctly 
    if remaining_words == ""
      @user_square.update(remaining_words: remaining_words) 
      @user_square.update(is_destroyed: true)
      redirect_to "/squares/#{params[:id]}?message=All%20words%20found!"
    
    # User guessed at least one word correctly
    elsif @user_square.remaining_words != remaining_words
      @user_square.update(remaining_words: remaining_words) 
      @image_path = generate_image(@user_square.remaining_words)
      @user_square.update(image_path: @image_path) 
      
      redirect_to "/squares/#{params[:id]}?message=correct"
    else 
      redirect_to "/squares/#{params[:id]}?message=incorrect"
    end

    end
end

app/helpers/squares_helper.rb
require 'httparty'
require 'base64'
require 'json'

module SquaresHelper
    def get_three_words(lat, lng)
        api_key = ENV['W3W_API_KEY']
        url = "https://api.what3words.com/v3/convert-to-3wa?coordinates=#{lat}%2C#{lng}&key=#{api_key}"
    
        response = HTTParty.get(url)
        
        if response.success?
          json_response = JSON.parse(response.body)
          p "JSON Response: #{json_response['words']}" 
          json_response['words']
        else
          # Handle error, maybe raise an exception or return an error message
          'Error fetching 3-word address'
        end
    end


      # app/helpers/image_generator_helper.rb


  # def generate_image(words)
    # return "squares/output_image.jpg"

  #   response = HTTParty.post("https://api.openai.com/v1/images/generations",
  #     headers: {
  #       "Authorization" => "Bearer #{ENV['OPENAI_API_KEY']}",
  #       "Content-Type" => "application/json"
  #     },
  #     body: {
  #       prompt: words,
  #       n: 1,
  #       size: "1024x1024"
  #     }.to_json
  #   )
    
  #   p response
  #   image_url = response['data'][0]['url']
    
  #   # Download the image and save it locally
  # File.open("output_image.jpg", 'wb') do |file|
  #   file.write open(image_url).read
  # end

  # Return the local file path
#   return "output_image.jpg"
# end 
# url = 'https://api.wizmodel.com/sdapi/v1/txt2img'
# api_key = ENV['WIZMODEL_API_KEY']

# payload = {
#   prompt: words,
#   steps: 50
# }.to_json

# headers = {
#   'Content-Type' => 'application/json',
#   'Authorization' => "Bearer #{api_key}"
# }

# response = HTTParty.post(url, headers: headers, body: payload)
# base64_string = JSON.parse(response.body)['images'][0]

# # Decode the base64 string into bytes
# image_data = Base64.decode64(base64_string)

# # Define the file path within the public/assets directory
# image_number = Time.now.to_i # Get a unique number for the image name
# file_name = "image#{image_number}.jpg"
# file_path = Rails.root.join('app', 'assets', 'images', 'squares', file_name)

# # Save the image to the specified file path
# File.open(file_path, 'wb') do |f|
#   f.write(image_data)
# end

# relative_path = file_path.relative_path_from(Rails.root.join('app', 'assets', 'images'))
# relative_path.to_s
# end

require 'aws-sdk-s3'

def generate_image(words)
  url = 'https://api.wizmodel.com/sdapi/v1/txt2img'
  api_key = ENV['WIZMODEL_API_KEY']

  payload = {
    prompt: words,
    steps: 50
  }.to_json

  headers = {
    'Content-Type' => 'application/json',
    'Authorization' => "Bearer #{api_key}"
  }

  response = HTTParty.post(url, headers: headers, body: payload)
  base64_string = JSON.parse(response.body)['images'][0]

  # Decode the base64 string into bytes
  image_data = Base64.decode64(base64_string)

  # Define the file name (object key)
  image_number = Time.now.to_i
  file_name = "image#{image_number}.jpg"
  aws_credentials = Rails.application.credentials.aws


  # Upload the image to S3 bucket
  s3 = Aws::S3::Resource.new(
    access_key_id: aws_credentials[:access_key_id],
    secret_access_key: aws_credentials[:secret_access_key],
    region: 'eu-west-2' # Change this to your desired AWS region
  )
  bucket = s3.bucket('ttsquaresdev')

  # Upload the image to the specified S3 bucket with the defined file name (object key)
  obj = bucket.object(file_name)
  obj.put(body: image_data, content_type: 'image/jpeg', acl: 'public-read')

  # Return the object key (file name) after uploading to S3 bucket
  file_name
end



  def get_remaining_words(square_words)
    square_words_array = square_words.split(' ')
    user_guesses_array = params[:words].split(' ')
    remaining_words = square_words_array - user_guesses_array
    return remaining_words.join(' ') 
  end 


  def get_display_words(remaining_words, square_words)
    square_words_array = square_words.split
    remaining_words_array = remaining_words.split
    # Replace words in square_words with asterisks if they exist in remaining_words
    result = square_words_array.map do |word|
      if remaining_words_array.include?(word)
        translate(word)
      else
        word
      end
    end 
    result.join(' ')
  end

  def translate(word)
    alphabet_dict = {"a"=>"▣", "b"=>"▤","c"=>"▥","d"=>"▦","e"=>"▧","f"=>"▨","g"=>"▩","h"=>"◧","i"=>"◨","j"=>"☰","k"=>"☱","l"=>"☲","m"=>"☳","n"=>"☴","o"=>"☵","p"=>"☶","q"=>"☷","r"=>"◩","s"=>"◪","t"=>"◫","u"=>"◰","v"=>"◱","w"=>"◲","x"=>"◳","y"=>"□","z"=>"■"}
    translated_word = ""
    for char in word.chars do
      print(translated_word)
      translated_word += alphabet_dict[char]
    end
    translated_word
  end

end

app/views/squares/error.html.erb
<div id="error-popup">
  <p><%= flash[:error] %></p>
</div>

<script>
  // JavaScript to close the error pop-up after 4 seconds
  setTimeout(function() {
    var errorPopup = document.getElementById('error-popup');
    if (errorPopup) {
      errorPopup.style.display = 'none';
    }
  }, 4000); // 4 seconds (4000 milliseconds)
</script>

app/views/squares/show.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="globals.css" />
    <link rel="stylesheet" href="styleguide.css" />
    <link rel="stylesheet" href="style.css" />
  </head>
  <body>
    <div class="square-macbook-pro">
      <div class="square-overlap-wrapper">
        <div class="square-overlap">
          <div class="square-frame">
          <div>
          <%= link_to 'LOG OUT', destroy_user_session_path, method: :delete, class:"logout_button" %>
        </div>
            <div class="square-overlap-group-wrapper">
              <div class="square-overlap-group">
                <div class="square-group-wrapper">
                  <div class="square-group">
                    <div class="square-div">
                      <%= image_tag "avatars/#{current_user.avatar_file}", class:"square-alien"%>
                      <div class="square-rectangle"></div>
                    </div>
                  </div>
                </div>
                <div class="square-overlap-2">
                  <div class="square-frame-2">
                    <div class="square-frame-wrapper">
                      <div class="square-frame-3">
                        <div class="square-overlap-group-2">
                          <p class="square-you-re-a-powerful">
                            YOU&#39;RE A POWERFUL ALIEN FORCE, HELL-BENT ON CONQUERING EARTH. YOUR MISSION: OBLITERATE
                            ALL RESISTANCE AND ESTABLISH DOMINANCE. HERE&#39;S YOUR GUIDE TO WREAK HAVOC...<br /><br />WEAKEN
                            EARTH&#39;S DEFENCES, SEIZE RESOURCES, AND CONTROL THE PLANET BY DEMOLISHING LANDMARKS
                            SQUARE BY SQUARE. EACH &#39;HUMANWORD&#39; CORRESPONDS TO UNIQUE COSMOS COORDINATES. USE
                            YOUR EXTRATERRESTRIAL INTELLECT TO UNVEIL EARTH&#39;S MYSTERIES.<br /><br />BEGIN ON EARTH’S
                            TERRAIN ARMED WITH A MAP.<br /><br />ENTERING YOUR GUESS:<br /><br />TYPE YOUR THREE-WORD
                            GUESS INTO THE INPUT FIELDS SHOWN.<br /><br />VERIFICATION:<br /><br />CORRECT WORDS TRIGGER
                            XENOLINGU, OUR LANGUAGE. WHEN ALL WORDS ARE CORRECT, THE MAP SQUARE CHANGES COLOUR. CLOSE?
                            HINTS FROM CORRUPT HUMANS GUIDE YOU.<br /><br />PROGRESSION:<br /><br />DECODE TO UNLOCK NEW
                            LEVELS. UNVEIL THE UNIVERSE&#39;S SECRETS.<br /><br />EMBARK ON &#39;INVASION EARTH:
                            ANNIHILATION PROTOCOL&#39;! CONQUER EARTH IN THIS OTHERWORLDLY ADVENTURE. BEST OF LUCK,
                            FEARLESS NEXARION!
                          </p>
                          <div class="square-text-wrapper">  <%= current_user.username %>  </div>
                        </div>
                        <div class="square-welcome-commander">WELCOME, COMMANDER:</div>
                      </div>
                    </div>
                  </div>
                  <div class="square-div-wrapper">
                    <div class="square-overlap-3">
                      <div class="square-overlap-group-3">
                        <div class="square-frame-4">
                          <div class="square-text-wrapper-2"><%= @display_words.split(" ")[0]%></div>
                          <div class="square-text-wrapper-2"><%= @display_words.split(" ")[1]%></div>
                          <div class="square-text-wrapper-2"><%= @display_words.split(" ")[2]%></div>
                          <div > <%= link_to image_tag("squares_page/icons8-x-48-1.png", class:"square-x"), "/" %> </div>
                        </div>
                      </div>
                      <% if @user_square.image_path.present? %>
                      <img src="<%= @s3_url %>" alt="Image Alt Text", class="square-ai-image">
                       
                      <% end %>
                      <div class="square-overlap-4">
                        <div>
                          <%= form_tag do %>
                            <%= text_field_tag :words, nil, class: 'custom-text-field', disabled: @user_square.is_destroyed %>
                            <%= submit_tag 'TRANSLATE', id: 'submit-button', class: 'translate_button', disabled: @user_square.is_destroyed == true %>
                          <% end %>
                        </div>
                        <div style="color: #FA143D;">
                          <p><%= @message %></p>
                          <% if flash.now[:alert] %>
                            <div class="alert alert-danger">
                              <%= flash.now[:alert] %>
                            </div>
                          <% elsif flash.now[:success] %>
                            <div class="alert alert-success">
                              <%= flash.now[:success] %>
                            </div>
                          <% end %>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="square-terrain-terminator">TERRAIN TERMINATOR</div>
        </div>
      </div>
    </div>
  </body>
</html>




<script>
  $(document).on('ready turbolinks:load', function () {
    $('#submit-button').on('click', function (e) {
      e.preventDefault();

      var formData = {
        word1: $('#words').val()

      };

      $.ajax({
        type: 'POST',
        url: '<%= squares_words_logic_path(@square) %>',
        data: formData,
        success: function(data) {
          // Update the image on the page
          $('#image-display').attr('src', data.image_path);
        },
        error: function() {
          alert('Error updating image.');
        }
      });
    });
  });
</script>

<style>
  .custom-text-field {
    background-color: #821CB1 !important;
    color: white !important;
    border: 5px solid #97b032 !important;
    border-radius: 20px;
    padding: 5px !important;
  }
  .translate_button {
    background-color: #97b032 !important;
    color: #16031c !important;
    border: 5px solid #97b032 !important;
    border-radius: 20px;
    padding: 5px !important;
    font-weight: bold;
  }
  .translate_button:hover {
    background-color: white !important;
    border: 5px solid white !important;
    cursor: pointer;
  }
  .logout_button {
  position: fixed;
  top: 20px;
  left: 20px;
  background-color: #97b032 !important;
  color: #16031c !important;
  border: 5px solid #97b032 !important;
  border-radius: 20px;
  padding: 5px !important;
  font-weight: bold;
  font-family: "Alegreya Sans", Helvetica;
}
.logout_button:hover {
  background-color: white !important;
  border: 5px solid white !important;
}
</style>